### ISSUE TITLE
Clipboard Copy Broken on OSX

### ISSUE THREAD

**Issue by sgolovine** [sgolovine/lip-to-clip#1]
Executing `lipsum $n`  causes the following error:

```/Users/sgolovine/.nvm/versions/node/v6.11.0/lib/node_modules/lip-to-clip/node_modules/execa/index.js:277
                throw (result.error || new Error(result.stderr === '' ? result.stdout : result.stderr));
                ^

Error
    at Function.module.exports.sync (/Users/sgolovine/.nvm/versions/node/v6.11.0/lib/node_modules/lip-to-clip/node_modules/execa/index.js:277:26)
    at Object.copySync (/Users/sgolovine/.nvm/versions/node/v6.11.0/lib/node_modules/lip-to-clip/node_modules/clipboardy/lib/macos.js:9:26)
    at Object.exports.writeSync.input [as writeSync] (/Users/sgolovine/.nvm/versions/node/v6.11.0/lib/node_modules/lip-to-clip/node_modules/clipboardy/index.js:38:13)
    at generate (/Users/sgolovine/.nvm/versions/node/v6.11.0/lib/node_modules/lip-to-clip/index.js:19:14)
    at wrapper (/Users/sgolovine/.nvm/versions/node/v6.11.0/lib/node_modules/lip-to-clip/index.js:25:3)
    at Object.<anonymous> (/Users/sgolovine/.nvm/versions/node/v6.11.0/lib/node_modules/lip-to-clip/index.js:28:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

**Comment by sgolovine** [comment]
Added OSX support via `pbcopy`.
